apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
spec:
  secretName: letsencrypt-cert
  dnsNames:
  - kibana.framsouza.co
  - monitoring.framsouza.co
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
