apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: fsouza@elastic.co
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      #name: issuer-letsencrypt-production
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx
