apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-prd
spec:
  version: 8.0.0
  count: 1
  elasticsearchRef:
    name: elastic-prd
  config:
    xpack.fleet.agents.elasticsearch.host: "https://elastic-prd-es-http.default.svc:9200"
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.default.svc:8220"]
    xpack.fleet.packages:
    - name: kubernetes
      version: 0.14.0
    xpack.fleet.agentPolicies:
    - name: Default Fleet Server on ECK policy
      is_default_fleet_server: true
      package_policies:
      - package:
          name: fleet_server
        name: fleet_server-1
    - name: Default Elastic Agent on ECK policy
      is_default: true
      unenroll_timeout: 900
      package_policies:
      - package:
          name: system
        name: system-1
      - package:
          name: kubernetes
        name: kubernetes-1
