apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic-prd
spec:
  version: 8.0.0
  count: 1
  elasticsearchRef:
    name: elastic-prd
  config:
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: monitoring
          namespace: monitoring
    logs:
      elasticsearchRefs:
        - name: monitoring
          namespace: monitoring
