---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring
  namespace: monitoring
spec:
  version: 8.0.0
  nodeSets:
  - name: es
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: monitoring
  namespace: monitoring
spec:
  version: 8.0.0
  count: 1
  elasticsearchRef:
    name: monitoring
