apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-hot
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
